services:
  server:
    build:
      context: .
      dockerfile: ./services/server/Dockerfile
      args:
        PORT: 81
    ports:
      - "81:81"
    restart: always
    env_file:
      - .env
  nginx:
    depends_on:
      - server
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
    ports:
      - "80:80"
    restart: always